# **MATRIX**

In [ ]:
import numpy as np

In [ ]:
A = np.array([
          [1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]])
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
A.shape

(3, 3)

In [ ]:
# vektor
a = np.array([1,2,3])
a

array([1, 2, 3])

In [ ]:
a.shape

(3,)

In [ ]:
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
hasil = A @ np.eye(3)
hasil

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

In [ ]:
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
A[1, -1]

6

In [ ]:
A[:, 2]

array([3, 6, 9])

In [ ]:
np.diag(np.diag(A))

array([[1, 0, 0],
       [0, 5, 0],
       [0, 0, 9]])

In [ ]:
np.zeros([5,5])

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

## **Operasi Aritmatika**

## **penjumlahan**

In [ ]:
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
B = np.array([[1, 0, 1],
              [4, 0, 2], 
              [0, 1, 1]])
B

array([[1, 0, 1],
       [4, 0, 2],
       [0, 1, 1]])

In [ ]:
# penjumlahan matriks terhadap skalar
A + 10

array([[11, 12, 13],
       [14, 15, 16],
       [17, 18, 19]])

In [ ]:
# penjumlahan matriks terhadap matriks
A + B

array([[ 2,  2,  4],
       [ 8,  5,  8],
       [ 7,  9, 10]])

In [ ]:
v = np.array([1, 2, 2])
A + v

array([[ 2,  4,  5],
       [ 5,  7,  8],
       [ 8, 10, 11]])

## **pengurangan**

In [ ]:
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
B

array([[1, 0, 1],
       [4, 0, 2],
       [0, 1, 1]])

In [ ]:
# pengurangan matriks terhadap skalar
A - 5

array([[-4, -3, -2],
       [-1,  0,  1],
       [ 2,  3,  4]])

In [ ]:
# pengurangan matriks terhadap matriks
A - B

array([[0, 2, 2],
       [0, 5, 4],
       [7, 7, 8]])

## **pembagian**

In [ ]:
# pembagian matriks terhadap skalar
A / 2

array([[0.5, 1. , 1.5],
       [2. , 2.5, 3. ],
       [3.5, 4. , 4.5]])

In [ ]:
# pembagian matriks terhadap matriks
A / B

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: RuntimeWarning: divide by zero encountered in true_divide
  


array([[ 1., inf,  3.],
       [ 1., inf,  3.],
       [inf,  8.,  9.]])

## **perkalian**

In [ ]:
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
B

array([[1, 0, 1],
       [4, 0, 2],
       [0, 1, 1]])

In [ ]:
# perkalian matriks terhadap skalar
A * 10

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [ ]:
# perkalian hadamard product (element-wise multiplication)
A * B

array([[ 1,  0,  3],
       [16,  0, 12],
       [ 0,  8,  9]])

In [ ]:
# perkalian matriks (@)
A1 = np.array([[1, 2, 1],
               [3, 0, 1],
               [1, 0, 0]])

B1 = np.array([[0, 1],
               [3, 1],
               [1, 0]])

In [ ]:
A1

array([[1, 2, 1],
       [3, 0, 1],
       [1, 0, 0]])

In [ ]:
B1

array([[0, 1],
       [3, 1],
       [1, 0]])

In [ ]:
A1 @ B1

array([[7, 3],
       [1, 3],
       [0, 1]])

## **Transpose**

In [ ]:
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
A.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [ ]:
B1

array([[0, 1],
       [3, 1],
       [1, 0]])

In [ ]:
B1.T

array([[0, 3, 1],
       [1, 1, 0]])

## **Inverse**

In [ ]:
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
np.linalg.inv(A)

LinAlgError: ignored

In [ ]:
B

array([[1, 0, 1],
       [4, 0, 2],
       [0, 1, 1]])

In [ ]:
inv_B = np.linalg.inv(B)
inv_B

array([[-1. ,  0.5,  0. ],
       [-2. ,  0.5,  1. ],
       [ 2. , -0.5,  0. ]])

In [ ]:
B @ inv_B

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
D = np.array([[1, 2, 1],
              [2, 4, 2],
              [5, 7, 4]])

D

array([[1, 2, 1],
       [2, 4, 2],
       [5, 7, 4]])

In [ ]:
np.linalg.inv(D)

LinAlgError: ignored

## **determinant**

In [ ]:
B

array([[1, 0, 1],
       [4, 0, 2],
       [0, 1, 1]])

In [ ]:
np.linalg.det(B)

2.0

In [ ]:
D

array([[1, 2, 1],
       [2, 4, 2],
       [5, 7, 4]])

In [ ]:
np.linalg.det(D)

0.0

In [ ]:
np.linalg.inv(D)

LinAlgError: ignored

## **Tensor**

In [ ]:
M1 = np.array([[1, 5, 3],
               [2, 7, 3]])

M2 = np.array([[4, 8, 3],
               [9, 7, 7]])

M3 = np.array([[2, 1, 0],
               [3, 0, 4]])

M4 = np.array([[5, 8, 5],
               [9, 1, 7]])

In [ ]:
T = np.array([M1, M2, M3, M4])
T

array([[[1, 5, 3],
        [2, 7, 3]],

       [[4, 8, 3],
        [9, 7, 7]],

       [[2, 1, 0],
        [3, 0, 4]],

       [[5, 8, 5],
        [9, 1, 7]]])

In [ ]:
T.shape

(4, 2, 3)